site_name: TanzoLang Documentation
site_description: Documentation for the TanzoLang schema specification
site_url: https://onalius.github.io/tanzo-lang-core/
repo_url: https://github.com/onalius/tanzo-lang-core
repo_name: onalius/tanzo-lang-core

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Schema Reference: schema.md
  - CLI Reference: cli.md
  - SDK References:
    - Python SDK: python-sdk.md
    - TypeScript SDK: typescript-sdk.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - attr_list
  - md_in_html

plugins:
  - search
  - autorefs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/onalius/tanzo-lang-core
  version:
    provider: mike

copyright: Copyright &copy; 2023 Tomodaichi Tanzo Team
