site_name: TanzoLang Documentation
site_description: Documentation for the TanzoLang schema specification and SDK
site_author: Onalius Team
site_url: https://onalius.github.io/tanzo-lang-core/

repo_name: onalius/tanzo-lang-core
repo_url: https://github.com/onalius/tanzo-lang-core
edit_uri: edit/main/docs/

theme:
  name: material
  logo: static/images/android-chrome-192x192.png
  favicon: static/images/favicon.ico
  palette:
    primary: deep-purple
    accent: deep-purple
  features:
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.tabs.link

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Philosophy & Purpose: philosophy.md
  - Schema: schema.md
  - Python SDK: python-sdk.md
  - TypeScript SDK: typescript-sdk.md
  - CLI: cli.md
  - Examples: examples.md
  - Ethics: ethics.md
  - GitHub: https://github.com/onalius/tanzo-lang-core

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_submodules: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/onalius/tanzo-lang-core
