site_name: TanzoLang Core
site_description: Documentation for the TanzoLang Core project
site_author: Onalius Team
site_url: https://onalius.github.io/tanzo-lang-core/

repo_name: onalius/tanzo-lang-core
repo_url: https://github.com/onalius/tanzo-lang-core
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Schema: schema.md
  - CLI Tool: cli.md
  - SDKs:
    - Python SDK: python-sdk.md
    - TypeScript SDK: typescript-sdk.md

plugins:
  - search
