site_name: TanzoLang Documentation
site_description: Documentation for the TanzoLang schema and tooling
site_author: Tomodaichi Tanzo Team
site_url: https://onalius.github.io/tanzo-lang-core/

repo_name: onalius/tanzo-lang-core
repo_url: https://github.com/onalius/tanzo-lang-core
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - Home: index.md
  - Schema Reference: schema.md
  - CLI Tools: cli.md
  - GitHub: https://github.com/onalius/tanzo-lang-core

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/onalius/tanzo-lang-core
