[tool.poetry]
name = "tanzo-schema"
version = "0.1.0"
description = "Python SDK for TanzoLang schema validation and utilities"
authors = ["Onalius Team <info@onalius.com>"]
readme = "README.md"
packages = [{include = "tanzo_schema"}]
license = "Apache-2.0"
repository = "https://github.com/onalius/tanzo-lang-core"
documentation = "https://onalius.github.io/tanzo-lang-core/"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.0.0"
jsonschema = "^4.17.3"
PyYAML = "^6.0"
numpy = "^1.24.0"

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
black = "^23.3.0"
mypy = "^1.3.0"
isort = "^5.12.0"
ruff = "^0.0.270"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tanzo-cli = "cli.tanzo-cli:main"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true

[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E", "F", "W", "I", "B", "C4", "ARG", "SIM"]
ignore = []

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"
addopts = "--cov=tanzo_schema --cov-report=term-missing --cov-report=xml --cov-report=html"
