site_name: TanzoLang Documentation
site_description: Documentation for the TanzoLang schema specification and tools
site_url: https://onalius.github.io/tanzo-lang-core/
repo_url: https://github.com/onalius/tanzo-lang-core
repo_name: onalius/tanzo-lang-core

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.code.copy

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Schema:
    - Overview: schema.md
    - Examples: schema-examples.md
  - CLI:
    - Overview: cli.md
    - Commands: cli-commands.md
  - SDKs:
    - Python: python-sdk.md
    - TypeScript: typescript-sdk.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/onalius/tanzo-lang-core
