site_name: TanzoLang Core Documentation
site_url: https://onalius.github.io/tanzo-lang-core/
repo_url: https://github.com/onalius/tanzo-lang-core
repo_name: onalius/tanzo-lang-core
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Schema Reference: schema.md
  - Usage Guide: usage.md

theme:
  name: material
  palette:
    primary: indigo
    accent: amber
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - toc:
      permalink: true

plugins:
  - search
