name: Test Manual pip Setup

on:
  push:
    branches: [main]
  pull_request:

jobs:
  manual-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Set up virtualenv and install via pip
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install numpy==1.26.4 --only-binary=:all:
          pip install -e .[dev]
          pytest -q
